server:
  port: 9090
spring:
  application:
    name: kafka
  kafka:
    bootstrap-servers: localhost:9092, localhost:9093
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: -1
      retries: 1
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-offset-reset: earliest
  datasource:
    url: "jdbc:postgresql://localhost:5432/kafka"
    driverClassName: "org.postgresql.Driver"
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.springframework: DEBUG
api:
  prefix: /kafka