server:
  port: 8081
spring:
  application:
    name: transaction-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      auto-offset-reset: earliest
  datasource:
    url: "jdbc:postgresql://localhost:5432/transaction-service"
    driverClassName: "org.postgresql.Driver"
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    stream-write-constraints:
      max-nesting-depth: 2000
logging:
  level:
    org.springframework: DEBUG
    org.springframework.kafka: DEBUG
    com.fasterxml.jackson: DEBUG
api:
  prefix: /transaction-service
